In [1]:
import tensorflow as tf

In [9]:
x = tf.reshape(tf.Variable(range(4), dtype=tf.float32),(4,1))
tf.print(x)

[[0]
 [1]
 [2]
 [3]]


In [11]:
with tf.GradientTape() as t:
    t.watch(x)
    y = 2 * tf.matmul(tf.transpose(x), x)

dy_dx = t.gradient(y, x)
tf.print(dy_dx)

[[0]
 [4]
 [8]
 [12]]


In [12]:
x

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [1.],
       [2.],
       [3.]], dtype=float32)>